---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    jkube.io/git-branch: master
    jkube.io/git-url: https://github.com/ravening/Visitor-Management-App.git
    jkube.io/git-commit: c923f536c53bce2cee834653b6a3279b5527ed9b
    jkube.io/scm-url: https://github.com/spring-projects/spring-boot/visitormanagmentapp
    jkube.io/scm-tag: HEAD
    jkube.io/issue-system: GitHub
    jkube.io/issue-tracker-url: https://github.com/spring-projects/spring-boot/issues
  labels:
    app: visitormanagmentapp
    provider: jkube
    version: 0.0.1
    group: com.rakeshv
  name: visitormanagmentapp
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: visitormanagmentapp
      provider: jkube
      group: com.rakeshv
  template:
    metadata:
      annotations:
        jkube.io/git-branch: master
        jkube.io/scm-url: https://github.com/spring-projects/spring-boot/visitormanagmentapp
        jkube.io/issue-system: GitHub
        jkube.io/issue-tracker-url: https://github.com/spring-projects/spring-boot/issues
        jkube.io/git-url: https://github.com/ravening/Visitor-Management-App.git
        jkube.io/scm-tag: HEAD
        jkube.io/git-commit: c923f536c53bce2cee834653b6a3279b5527ed9b
      labels:
        app: visitormanagmentapp
        provider: jkube
        version: 0.0.1
        group: com.rakeshv
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: visitor-managment
        imagePullPolicy: Never
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        securityContext:
          privileged: false
