---
apiVersion: v1
kind: Service
metadata:
  annotations:
    jkube.io/git-branch: master
    jkube.io/git-url: https://github.com/ravening/Visitor-Management-App.git
    jkube.io/git-commit: c923f536c53bce2cee834653b6a3279b5527ed9b
    jkube.io/scm-url: https://github.com/spring-projects/spring-boot/visitormanagmentapp
    jkube.io/scm-tag: HEAD
    jkube.io/issue-system: GitHub
    jkube.io/issue-tracker-url: https://github.com/spring-projects/spring-boot/issues
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    app: visitormanagmentapp
    provider: jkube
    version: 0.0.1
    group: com.rakeshv
  name: visitormanagmentapp
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: visitormanagmentapp
    provider: jkube
    group: com.rakeshv
